### ISSUE TITLE
How to set value without using setInterval()?

### ISSUE THREAD

**Issue by roelzkie15** [sebhildebrandt/ng-sparkline-seriesbar#1]
This directive is pretty however it is lacking functionality or i just missed it.

I tested the demo and i got this working
![recording](https://cloud.githubusercontent.com/assets/20513403/23509248/24bfb43a-ff90-11e6-877d-49c9cfd9c650.gif)

But if i defined the `value=[1,2,3,4,5,6,7,8,9,10]` without using `setInterval()` i got this one:
![untitled](https://cloud.githubusercontent.com/assets/20513403/23509410/a4199eda-ff90-11e6-9ac9-232b8a6c4069.png)

What i expect is something like this one:
![screenshot](https://cloud.githubusercontent.com/assets/20513403/23509457/d9cf0f2e-ff90-11e6-9479-675932fdc14a.jpeg)

This is of course is a simple screenshoot from the animated gif. How can i initialized the data?

I really love this work thanks!

**Comment by sebhildebrandt** [comment]
Updated the repo, didn't know, that still someone uses it ;-)
So what you basically have to do is:

`points="[1,2,3,4,5,6,7,8,9,10]"`

and do NOT use the `value` attribute at all, because this would then be the first parameter so something like this is fine:

```
<ng-sparkline-seriesbar id="sparky" height=20 max-points=10 chart-range-min=0 points="[1,2,3,4,5,6,7,8,9,10]"></ng-sparkline-seriesbar>
```
